blank_issues_enabled: false

contact_links:
  - name: Share and discuss ideas
    url: https://github.com/atomic-junky/tasty-supplies/discussions
    about: Discuss any idea related to improving Tasty Supplies.