BUTTER = "poisonous_potato"
PIE_CRUST = "angler_pottery_sherd"
RICE = "archer_pottery_sherd"
COOKED_RICE = "field_masoned_banner_pattern"
RAW_SALMON_SLICE = "bordure_indented_banner_pattern"
RAW_COD_SLICE = "flower_banner_pattern"
