name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"

env:
  PYTHON_VERSION: "3.12.2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build project
        run: beet -p ./tasty_supplies build

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./tasty_supplies/build/
          compression-level: 0
      
      - name: Create release
        uses: ncipollo/release-action@v1.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          name: Monologue ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.build_directory }}/**/*
          replacesArtifacts: true
          prerelease: ${{ contains(fromJSON('["dev", "pre", "alpha", "beta", "rc"]'), github.event_name) }}
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
                **Build ${{ github.ref_name }}**

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          assets: ./build-artifacts.zip