name: Build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.14.3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build project
        run: beet -p ./tasty_supplies build
      
      - name: Zip all builds
        run: |
          cd ./tasty_supplies/build/
          for dir in *; do
            cd "./$dir"
            zip -r "../$dir.zip" ./*
            cd ..
          done
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          files: ./tasty_supplies/build/*.zip
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
      
      - name: Modrinth Upload
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: SLkQznH5
          version: ${{ github.ref_name }}
          changelog: ${{ steps.changelog.outputs.changes }}
          loaders: |-
            datapack
            minecraft
          game-versions: |-
            26.2
            26.1.x
            1.21.11
          environment: client_and_server
          primary-file: TastySupplies_-_DataPack.zip
          files: '["tasty_supplies/build/TastySupplies_-_DataPack.zip", "tasty_supplies/build/TastySupplies_-_ResourcePack.zip"]'
          file-types: TastySupplies_-_ResourcePack.zip=required-resource-pack
          channel: beta
          name: v${{ github.ref_name }}

      - name: Curseforge Upload (Resource Pack)
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: ./tasty_supplies/build/TastySupplies_-_ResourcePack.zip
          game_endpoint: "minecraft"
          relations: "fabric-api:requiredDependency"
          game_versions: "Minecraft 1.21.11:26.2"
          project_id: 1362637
          token: "${{ secrets.CF_API_TOKEN }}"
          display_name: "[v${{ github.ref_name }}] Tasty Supplies - Resource Pack"
          changelog: ${{ steps.changelog.outputs.changes }}
          changelog_type: "markdown"
          release_type: "release"

      - name: Curseforge Upload (Data Pack)
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: ./tasty_supplies/build/TastySupplies_-_DataPack.zip
          game_endpoint: "minecraft"
          relations: "fabric-api:requiredDependency"
          game_versions: "Minecraft 1.21.11:26.2"
          project_id: 1362637
          token: "${{ secrets.CF_API_TOKEN }}"
          display_name: "[v${{ github.ref_name }}] Tasty Supplies - Data Pack"
          changelog: ${{ steps.changelog.outputs.changes }}
          changelog_type: "markdown"
          release_type: "release"