name: Build

on: [push, pull_request]

env:
  PYTHON_VERSION: "3.14.3"

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build project
        run: beet -p ./tasty_supplies build
      
      - name: Zip all builds
        run: |
          cd ./tasty_supplies/build/
          for dir in *; do
            cd "./$dir"
            zip -r "../$dir.zip" ./*
            cd ..
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: builds
          path: ./tasty_supplies/build/*.zip